apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: demo-binding
spec:
  type: bindings.redis
  metadata:
  - name: redisHost
    value: redis-master.default.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis
      key: redis-password